### ISSUE TITLE
Form Control Name?

### ISSUE THREAD

**Issue by carlhussey** [psilospore/ng-next-select#11]
I found this fork from the comments in the original repo. Does this build include the `formControl` functionality ?

**Comment by psilospore** [comment]
Not at the moment. I have a PR here with a really minor conflict here https://github.com/psilospore/ng-next-select/pull/1

However in the original PR https://github.com/valor-software/ng2-select/pull/758#pullrequestreview-31186930 someone mentioned it was already supported but I don't believe I was able to do that. So I was supposed to verify if that was true, but got bogged down with work and now I currently don't work at the company where I built it or really use Angular now.

If you or someone else would be willing to verify that formControl is not supported with this library then I or one of the maintainers could merge that PR and publish the changes.

Thanks for looking into this fork btw!

**Comment by carlhussey** [comment]
I have spent about an hour trying to get it to work on the original library without success. I verified that when trying to call methods on the input such as `this.importForm.controls['costCenter'].disable()`, the input field remained unchanged. Inspected the actual form element after invoking the method and saw that the form did toggle its status to disabled but the input it self did not reflect this.

**Comment by psilospore** [comment]
Cool I decided to merge since it seems that me, you, and other people all had trouble with FormControls. I will try to publish an update on npm tomorrow.

**Comment by carlhussey** [comment]
Awesome, thanks for the quick replies! This is the one feature preventing me from closing out a project so I really appreciate it :)

**Comment by psilospore** [comment]
No problem! I'm just glad other people are interested in this fork 🙂

**Comment by psilospore** [comment]
Hey sorry had a pretty hectic morning but I just published the Form Control changes I believe. If you update to 1.3.13 it should be functional. Let me know if you run into any issues. Thanks!

**Comment by carlhussey** [comment]
Thanks for the update!

I seem to be having a little trouble or maybe I am just doing something incorrectly here.

Here is my HTML with my select input.
```
<form [formGroup]="importForm" #f="ngForm" *ngIf="fields" [hidden]="showLoader">
    <div class="form-group">
        <div class="input-group">
            <ng-select formControlName="costCenter" [allowClear]="true" [multiple]="true" [items]="getCostCenters()" placeholder="Select one or more Cost Centers">
            </ng-select>
            <span class="input-group-btn">
          <button class="btn btn-sm btn-default" type="button" title="Update Filter" (click)="test()"><i class="fa fa-filter"></i></button>
        </span>
        </div>
    </div>
</form>
```

**Component:**
```
ngOnInit() {
    this.importForm = this.fb.group({
        costCenter: [
            []
        ]
    });
}

test() {
    this.importForm.controls['costCenter'].disable()
}
```

When I click on the button, I am trying to disable the ng-select input through the formControls but it doesn't get toggled.

Am I overlooking something?

**Comment by psilospore** [comment]
So it's been a while but I think with my changes I didn't support formGroup so you would need to pass it in like this

<ng-select [formControl]="formGroup.formControl" ...>

**Comment by carlhussey** [comment]
Awesome, that took care of it. Thanks so much - I have another question I am going to open and run by you ;)
