### ISSUE TITLE
Integrate Pull Request for closing off click

### ISSUE THREAD

**Issue by carlhussey** [psilospore/ng-next-select#12]
Are you able to add in this pull request to your build? I have about 8 selects on a page and if you click on one, and then another, they all just stay open.

This pull looks like it will address the issue by closing others when clicking on a new one.

Thoughts?

https://github.com/valor-software/ng2-select/pull/712

**Comment by psilospore** [comment]
Sure I can request the creator of that PR to open a PR to my fork as well

**Comment by psilospore** [comment]
Actually I was just able to create a PR anyway https://github.com/psilospore/ng-next-select/pull/13

However there are merge conflicts. Maybe you or someone else could create another PR that resolves those merge conflicts. I'm betting the conflicts aren't anything major.

**Comment by carlhussey** [comment]
I will try and figure that out - pretty new to git so I will need to determine what those conflicts are to be able to address them. Will try and update you shortly.

**Comment by psilospore** [comment]
@carlhussey hey sorry I went on vacation and forgot to reply, but I meant to tell you if you ever want help I don't mind hopping on a screenshare.

**Comment by carlhussey** [comment]
Thanks for the reply - I will probably try and tackle this over the
weekend. I have a big need for it now, just gotta figure out how to use git
in order to test and fix the conflicts.
